import { FoodItem } from './types';

// 示例食物数据库（当 Supabase 未配置时使用）
export const sampleFoods: FoodItem[] = [
  {
    id: '1',
    name: '动物内脏（肝、肾、胰）',
 嘌呤: '高',
    gi: '中',
    risk: '高尿酸血症、痛风患者应避免食用',
    alternatives: ['豆腐', '鸡胸肉', '鱼肉'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: '沙丁鱼',
 嘌呤: '高',
    gi: '低',
    risk: '高尿酸血症、痛风患者应避免食用',
    alternatives: ['三文鱼', '鳕鱼', '虾'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: '白米饭',
 嘌呤: '低',
    gi: '高',
    risk: '糖尿病患者应控制摄入量',
    alternatives: ['糙米', '燕麦', '全麦面包'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: '白面包',
 嘌呤: '低',
    gi: '高',
    risk: '糖尿病患者应控制摄入量',
    alternatives: ['全麦面包', '燕麦', '糙米'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: '西兰花',
 嘌呤: '低',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['菠菜', '油菜', '白菜'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: '苹果',
 嘌呤: '低',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['梨', '柚子', '草莓'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    name: '香蕉',
 嘌呤: '低',
    gi: '中',
    risk: '糖尿病患者应控制摄入量',
    alternatives: ['柚子', '草莓', '蓝莓'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '8',
    name: '啤酒',
 嘌呤: '高',
    gi: '低',
    risk: '高尿酸血症、痛风患者应避免饮酒',
    alternatives: ['水', '无糖茶', '苏打水'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    name: '鸡蛋',
 嘌呤: '中',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['豆腐', '鸡胸肉', '鱼肉'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    name: '牛奶',
 嘌呤: '低',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['酸奶', '奶酪', '豆奶'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '11',
    name: '蜂蜜',
 嘌呤: '低',
    gi: '高',
    risk: '糖尿病患者应控制摄入量',
    alternatives: ['代糖', ' Stevia', '少量水果'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    name: '蛋糕',
 嘌呤: '低',
    gi: '高',
    risk: '糖尿病患者应避免食用',
    alternatives: ['无糖酸奶', '坚果', '水果'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '13',
    name: '牛肉',
 嘌呤: '中',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['鸡胸肉', '鱼肉', '豆腐'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '14',
    name: '羊肉',
 嘌呤: '中',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['鸡胸肉', '鱼肉', '豆腐'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '15',
    name: '猪肉',
 嘌呤: '中',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['鸡胸肉', '鱼肉', '豆腐'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '16',
    name: '虾',
 嘌呤: '中',
    gi: '低',
    risk: '高尿酸血症患者应适量食用',
    alternatives: ['鱼肉', '鸡胸肉', '豆腐'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '17',
    name: '龙虾',
 嘌呤: '高',
    gi: '低',
    risk: '高尿酸血症、痛风患者应避免食用',
    alternatives: ['鱼肉', '鸡胸肉', '豆腐'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '18',
    name: '扇贝',
 嘌呤: '高',
    gi: '低',
    risk: '高尿酸血症、痛风患者应避免食用',
    alternatives: ['鱼肉', '鸡胸肉', '豆腐'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '19',
    name: '菠菜',
 嘌呤: '中',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['西兰花', '油菜', '白菜'],
    createdAt: new Date().toISOString(),
  },
  {
    id: '20',
    name: '蘑菇',
 嘌呤: '中',
    gi: '低',
    risk: '无特殊风险',
    alternatives: ['西兰花', '白菜', '胡萝卜'],
    createdAt: new Date().toISOString(),
  },
];

// 根据食物名称查找食物信息
export const findFoodByName = (name: string): FoodItem | undefined => {
  return sampleFoods.find((food) => food.name === name);
};

// 获取所有食物名称
export const getAllFoodNames = (): string[] => {
  return sampleFoods.map((food) => food.name);
};